global:
  scrape_interval:     10s
  scrape_timeout:       5s
  evaluation_interval: 10s

scrape_configs:
- job_name: 'prometheus-playground'
  static_configs:
    - targets: [ 'prometheus-playground:9000' ]
#- job_name: 'prometheus'
#  static_configs:
#    - targets: [ 'localhost:9090' ]
#- job_name: 'tempo'
#  static_configs:
#    - targets: [ 'tempo:3200' ]
