version: '3.7'

services:
  proxy:
    image: nginx
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  backend1:
    image: nginx
    ports:
      - '9991:80'
  backend2:
    image: nginx
    ports:
      - '9992:80'
  backend3:
    image: nginx
    ports:
      - '9993:80'
