version: '3.7'

volumes:
  jiravolume: {}

services:
  mysql:
    image: mysql:5.6
    container_name: mysqldb
    environment:
        - 'MYSQL_ROOT_PASSWORD=jiradb'
        - 'MYSQL_DATABASE=jiradb'
        - 'MYSQL_USER=jiradb'
        - 'MYSQL_PASSWORD=jiradb'
    ports:
      - "3306:3306"
    restart: unless-stopped

  jira:
    image: teamatldocker/jira
    container_name: jira
    volumes:
      - "jiravolume:/var/atlassian/jira"
    environment:
      - "JIRA_DATABASE_URL=mysql://jiradb@mysql/jiradb"
      - "JIRA_DB_PASSWORD=jiradb"
    ports:
      - "80:8080"
    restart: unless-stopped
